### ISSUE TITLE
Optimization work details

### ISSUE THREAD

**Issue by yvanblanchard** [fly2mars/CFRPco-extrusionOptimization#1]
Hello,

Could you please share explanations (maybe paper or thesis report document) about your optimization work (context and results)?

Thank you for sharing !

**Comment by fly2mars** [comment]
Sorry I just saw the news. You can see the details in this paper. 

An adaptive matrix material extrusion optimization model for in situ impregnated continuous fiber-reinforced 3D printing
https://link.springer.com/article/10.1007/s00170-023-12284-2

Here the difference between the deposition spacing in the path and the set deposition spacing is calculated. It is further used for the compensation of the matrix extrusion.

**Comment by yvanblanchard** [comment]
Thank you ! very interesting work.
Can't wait for getting and testing the code on my GCode files!
